repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy (local)
        entry: mypy
        language: system
        pass_filenames: false
        args: ["src"]
        types: [python]
